### ISSUE TITLE
Don't add configuration to project if configuration fails to be created

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#241] opened 2022-12-16 09:52 UTC
1. `bdep new -t lib libhello`
2. `mkdir libhello-msvc`
3. `cd libhello`
4. `bdep init -C @msvc cc config.cxx=cl.exe`

This will fail with (expected):
```
error: directory ../libhello-msvc/ is not empty
  info: use --wipe to clean it up but be careful
```

And then you use `--wipe` and it fails with (unexpected):
```
error: configuration with name 'msvc' already exists in project <path-to-project>
```

**Note:** Could have been only an issue in VS Dev Prompt, since I tried this in WSL and didn't see the same issue with gcc. But that could also have been a coincident.

**Comment by Klaim** [comment] 2022-12-16 10:47
Just so my understanding is correct: the first error suggests you already  have that directory for another project, right?
So you expect `--wipe` to remove that other project from that configuration (and everything else) without a warning? Or with a warning but not preventing it?

**Comment by helmesjo** [comment] 2022-12-16 11:29
The first error is expected, the second is (IMO) not expected (since it failed to create the configuration, I don't expect it to have been added). I updated the description to make it more clear.

**Comment by Klaim** [comment] 2022-12-16 11:53
Ah yes, this is actually an historically common issue: there are other situations (basically any error at the first `bdep init` invocation) where it is surprising and confusing that the configuration is added but also not usable (which is why at some point I asked for a way to nuke known configs from both the db and disk, for now doing it manually when this situation arise).
I believe there might be other tickets related to this.

**Comment by wroyca** [comment] 2022-12-16 11:55
I can confirm, I was mitigating that with an alias to nuke things

**Comment by boris-kolpackov** [comment] 2023-06-09 06:04
I am unable to reproduce this, neither on Linux nor on Windows (MSVC 17.4 Dev prompt) using the latest staged toolchain. Specifically:

First of all, if I follow your instructions, I don't get the "directory is not empty" error (because it is empty), neither on Windows nor on Linux.

Secondly, if additionally I make it not empty, the second command with `--wipe` succeeds:

```
bdep new -t lib libhello
mkdir libhello-msvc
echo junk >libhello-msvc/junk
cd libhello

bdep init -C @msvc cc config.cxx=cl.exe
error: directory ../libhello-msvc/ is not empty
  info: use --wipe to clean it up but be careful
  
bdep init --wipe -C @msvc cc config.cxx=cl.exe
```

I've also reviewed the relevant code and I don't see how we could possibly be adding the configuration to the database after this error. The error throws an exception and we simply don't get to execute the "add" part.

**Comment by Klaim** [comment] 2023-06-09 10:17
I think I managed to reproduce (with recent stage version) the issue or a similar issue with:
```
bdep new -t lib libhello
cd libhello
bdep init -C @msvc cc config.cxx=cl.exe
bdep init --wipe -C @msvc cc config.cxx=cl.exe
```
output:
```
created new library project libhello in E:\tests\build2-241\libhello\
initializing in project E:\tests\build2-241\libhello\
created configuration @msvc E:\tests\build2-241\libhello-msvc\ 1 target default,forwarded,auto-synchronized
synchronizing:
  new libhello/0.1.0-a.0.19700101000000
initializing in project E:\tests\build2-241\libhello\
error: configuration with name 'msvc' already exists in project E:\tests\build2-241\libhello\
```

But this is kind of a different report than the initial one, the difference are:
- This appears when the directory we want to wipe was already a configuration known and named, which was not the case in the initial report;
- The error is actually about the name we attempt to re-assigned on the second init command, which is considered an error even if `--wipe` is used - the error is the same being reported initially, so it must have been from the same source;
- these previous points suggests that @helmesjo tried to run a second `bdep init --wipe` command immediately after the first `bdep init` error. Following exactly the repro case will not reproduce the issue without trying the last instruction a second time with `--wipe` added. Restarting the repro from scratch and using `--wipe` in the first `bdep init` will also not trigger the error, as expected. That would match @boris-kolpackov's observations.

This basically means that `--wipe` cannot work in that situation where we created a configuration already (and it failed or not) and  we want to use `--wipe` to "recreate" or "fix because there was an error" by re-running the `bdep init` command and just adding `--wipe`. This is what often happens in my experience (which lead me to take the habit of just nuking everything and re-creating configs from scratch instead of using `--wipe`). 
Maybe it's user's fault for thinking of `--wipe` as a generic "please overwrite" instruction, it's not that simple when the directory is a configuration where the project is initialized...

Note that my initial interpretation of the initial report was probably misleading, sorry about that!

**Comment by boris-kolpackov** [comment] 2023-06-12 13:23
> Maybe it's user's fault for thinking of `--wipe` as a generic "please overwrite" instruction, it's not that simple when the directory is a configuration where the project is initialized...

Yes, this is a familiar story: There is a step by step way of doing things (`bdep config create @gcc ...` && `bdep init @gcc`) but the user complains it's too tedious. So we add a shortcut (`bdep init -C @gcc ...`) and document it as being equivalent to performing the two separate steps one after the other. The user skips reading the documentation and starts expecting the shortcut to magically do exactly what they expect in every situation.

In any case, I've added some extra code to check for configuration clashes before creating/wiping the configuration. So your example now produces:

```
initializing in project /tmp/libhello/
created configuration @msvc /tmp/libhello-msvc/ 1 target default,forwarded,auto-synchronized
synchronizing:
  new libhello/0.1.0-a.0.19700101000000

initializing in project /tmp/libhello/
error: configuration with name 'msvc' already exists in project /tmp/libhello/
  info: use 'bdep config remove @msvc' to remove
```

Note that unlike the old behavior, now the configuration is not wiped prior to issuing the error.

I think this is as far as I am willing to take for now. So I am going to close this issue. The fix will be available in tomorrow's staged toolchain.

**Closed by boris-kolpackov** 2023-06-12 13:23 UTC
Labels: bug, windows

**Comment by helmesjo** [comment] 2023-06-12 13:57
Sorry for being late to the party.
But ok, if it can't be reproduced anymore (I remember trying it multiple times with a clean slate and indeed could reproduce the initial error), then I assume it's been fixed anyways.

Thanks!
