### ISSUE TITLE
Assertion in to_stream() with incorrect library path

### ISSUE THREAD

**Issue by boris-kolpackov** [build2/build2#170] opened 2021-10-26 12:43 UTC
From odb-users mailing list:

```
> % bpkg build libodb-sqlite "?sys:libodb/*" "?sys:libsqlite3/*"
> configured sys:libsqlite3/*
> configured sys:libodb/*
> using libodb-sqlite/2.5.0-b.19 (external)
> error: unable to import target libsqlite3%lib{sqlite3}
>   info: use config.import.libsqlite3 configuration variable to specify its project out_root
>   info: or use config.import.libsqlite3.sqlite3.lib configuration variable to specify its path
> error: unable to import target libsqlite3%lib{sqlite3}
>   info: use config.import.libsqlite3 configuration variable to specify its project out_root
>   info: or use config.import.libsqlite3.sqlite3.lib configuration variable to specify its path

So, as instructed, I added "config.import.libsqlite3.sqlite3.lib=/usr/local/opt/sqlite3/lib" (containing libsqlite3.a and libsqlite3.dylib) during build, and got this:

> % bpkg build libodb-sqlite "?sys:libodb/*" "?sys:libsqlite3/*"
> Assertion failed: (!k.ext), function to_stream, file /private/tmp/build2-20210930-54042-1y6y00/build2-toolchain-0.13.0/build2/libbuild2/target.cxx, line 550.
```

**Comment by karen-arutyunov** [comment] 2021-11-22 11:10
The issue is fixed in build2 version 0.14.0 (commit bcb9588ea24d).

**Closed by karen-arutyunov** 2021-11-22 11:10 UTC
