### ISSUE TITLE
Building build2 with debug information

### ISSUE THREAD

**Issue by kamrann** [build2/build2#200] opened 2022-07-26 10:42 UTC
For purposes of bug investigation and reporting, I'd prefer to have `build2` always built with debugging symbols. Since they're off by default (at least with the MSVC install scripts), this has involved using the manual install steps (slow), or modifying things post-installation and rebuilding (also slow and I frequently break things).
Could an option be added to the scripts to make tweaks like this a little easier to achieve without going the full manual install route? Or perhaps just enable debug information by default for the staged toolchain script?

**Comment by boris-kolpackov** [comment] 2022-07-26 16:20
This should be doable. I don't think building with debug (and presumably without optimization) by default is a good idea since an unoptimized toolchain is noticably slower (especially if something like Boost is involved). So to me an option to the install script to disable optimization and enable debug information seems like the best approach. Thoughts?

**Comment by kamrann** [comment] 2022-07-26 17:39
I agree optimization shouldn't be disabled by default, as you say it would be a lot slower so I wouldn't want my installation to have optimizations disabled. But I think a lot can be gained from having debug info on whilst retaining optimizations. I currently have (with MSVC):
```
config.cc.coptions = /O2 /Zi
config.cc.loptions = /DEBUG:FULL
```
This allows for reasonable debugging without any (as far as I'm aware) real overhead. So regardless of chosen default, I think if options are added to the script, ideally optimization and debug info should be individual toggles.

**Comment by boris-kolpackov** [comment] 2022-08-15 14:19
This is getting a bit messy. Specifically:

1. Maybe it's different in the MSVC land, but our experience with GCC is that optimized debug builds are pretty much useless because the source positions are invariably off and you cannot see the value of half of the variables (because they were optimized out). So I don't think "optimized debug" should be the default. But perhaps we could add a separate install script option, for example, `--debug` and `--debug-optimized`.

2. As you are probably aware, the install scripts delegate the actual building to the `build` script/batch files inside `build2-toolchain`. While there is a mechanism for passing additional compiler options, there is no support for passing additional linker options and adding this support cleanly will not be easy (the additional compiler options are passed as trailing arguments to the build script since that's the only "proper array" available in POSIX shell).

So passing `/DEBUG:FULL` is going to be problematic. On the other hand, if we use `/Z7` instead of `/Zi`, then we don't need `/DEBUG`. In our (admittedly limited) testing `/Z7` appears to be pretty usable. It also has the added benefit of not having to worry about locating `.pdb` files. Any experience with this on your side?

**Comment by Klaim** [comment] 2022-08-15 15:06
> Maybe it's different in the MSVC land

Release with debug info builds with msvc have similarly optimized out calls and variables (probably differently than gcc or clang), but it's often still enough to figure out some categories of bugs (and it's the default in game development for example, where it's hard to reproduce issues without the program being performant).

> So I don't think "optimized debug" should be the default. But perhaps we could add a separate install script option, for example, `--debug` and `--debug-optimized`.

I think that's the best way to do it.

**Comment by kamrann** [comment] 2022-08-15 17:40
Yep, completely on board with the default remaining as it is.

My motivation for this is that I definitely want optimizations on for my regular `build2` installation; but if I have debug info then it means I can dig into issues as I hit them, and not have to faff around trying to reproduce it on a secondary, debug installation (which I'd assume would probably mean a separate build configuration for the project too, or at the very least require me to make sure my two installations are always in version sync). Certainly any serious debugging would warrant a full debug build, but an optimized debug info build would let me narrow down the cause greatly and make filing an issue with useful info much quicker.

>    So passing `/DEBUG:FULL` is going to be problematic. On the other hand, if we use `/Z7` instead of `/Zi`, then we don't need `/DEBUG`. In our (admittedly limited) testing `/Z7` appears to be pretty usable. It also has the added benefit of not having to worry about locating `.pdb` files. Any experience with this on your side?

It's been ages since I used `/Z7`, I couldn't say anything useful off hand. But if that's the easiest way to go for now, then I'd say it's definitely worth trying out.

**Comment by boris-kolpackov** [comment] 2022-08-22 10:51
The install scripts/batch files for the latest staged toolchain now support the `--debug` and `--debug-optimized` options. It would be great if you could give it a try and confirm things work as expected.

Also, a couple of corrections to the previous comments: it turns out the only way to have debug information for an executable or DLL on Windows with MSVC is as  a separate `.pdb` file and the only way to produce it is with the `/DEBUG` linker option. What `/Z7` does (compared to /Zi`) is suppress the generation of the `.pdb` file per translation unit and instead embed the debug info directly into the object file (but which still ends up in the `.pdb` file of an EXE/DLL). As a result, the batch files pass `/Zi` instead of `/Z7` as originally planned and also pass `/DEBUG:FULL`.

Also, as a note to anyone wondering, when Clang targets MSVC, `-g` appears to be equivalent to `/Zi` (that is, the debug info is placed into the object file).

**Comment by boris-kolpackov** [comment] 2023-04-05 09:24
This fix has been out for a while now without any new complaints so far, so I am going to close this issue to keep things organized. But feel free to reopen if there are still any issues.

**Closed by boris-kolpackov** 2023-04-05 09:24 UTC
Labels: enhancement
