### ISSUE TITLE
Build2 failed when build with permissive- by msvc on Windows 

### ISSUE THREAD

**Issue by QuellaZhang** [build2/build2#78] opened 2020-02-07 10:49 UTC
Build2 failed with error C2440 when build with permissive- by msvc on Windows. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**repro step:**
open VS x64 command tools
set CL=/permissive-
build-msvc.bat --trust yes --verbose 2

**Failures:**
F:\gitP\Build2\build2-toolchain-0.13-a.0\build2-0.13.0-a.0.20200203134539.8efa97024e4a\libbuild2\cc\module.cxx(605): error C2440: 'initializing': cannot convert from 'build2::dir_paths' to 'build2::dir_paths &'
F:\gitP\Build2\build2-toolchain-0.13-a.0\build2-0.13.0-a.0.20200203134539.8efa97024e4a\libbuild2\cc\module.cxx(605): note: A non-const reference may only be bound to an lvalue

**Comment by boris-kolpackov** [comment] 2020-02-07 14:25
Some time ago we have tried to enable `/permissive-` for the `build2` builds but that triggered too many bugs in MSVC. The code in question looks like this:

`
auto& mods (mod_dirs ? mod_dirs->first : dir_paths ());
`

Other compilers (including latest versions of GCC and Clang in the `-Wall -Wextra` mode) are all able to deduce the type as `const dir_path&` but not MSVC, which thinks it's `dir_path&`.

If you would like, you can report this to the Visual Studio team. But until all such issues are addressed, I don't think we can disable the permissive mode.

**Comment by QuellaZhang** [comment] 2020-02-11 09:25
Thanks, I am confirming with them now.

**Comment by boris-kolpackov** [comment] 2020-07-24 13:12
Any update on this? I am tempted to close this since this doesn't seem to be our bug.

**Comment by boris-kolpackov** [comment] 2020-08-21 03:49
Ok, I am closing this since there is no feedback and it appears the issue is not on our side. Feel free to reopen if/when you think we can do something about this.

**Closed by boris-kolpackov** 2020-08-21 03:49 UTC
