### ISSUE TITLE
error: unknown Compiled Module Interface: malformed error response

### ISSUE THREAD

**Issue by NothcixConfictura** [build2/build2#203] opened 2022-08-05 14:58 UTC
I just read [this particular article](https://build2.org/blog/build2-cxx20-modules-gcc.xhtml) after finding out about the C++ Modules TS, so I tried it out:
```c++
// hello.mxx
export module hello;

import <string_view>;
import <iostream>;

export namespace hello {
    void say_hello(const std::string_view &name) {
        std::cout << "Hello, " << name << '!' << std::endl;
    }
}
```
```c++
// hello.cxx
import hello;

int main(int argc, char *argv[]) {
    hello::say_hello("World");
}
```
```buildfile
// buildfile
cxx.std = experimental
cxx.features.modules = true

using cxx

assert $cxx.features.modules "no modules support for $cxx.signature"

mxx{*}: extension = mxx
cxx{*}: extension = cxx

exe{hello}: {cxx mxx}{*}
```

Then I proceeded to compile the simple project by running `b -sV`, but it errors and outputs the following:
```
g++ -v
g++ -print-multiarch
g++ -dumpmachine
g++ -x c++ -E -
bin @C:\Users\█████\min\
  target     x86_64-w64-mingw32
ar --version
bin.ar @C:\Users\█████\min\
  ar         ar@C:\_C++\bin\ar.exe
  id         gnu
  version    2.38.0
  major      2
  minor      38
  patch      0
  signature  GNU ar (Binutils for MinGW-W64 x86_64, built by Brecht Sanders) 2.38
  checksum   2f4bfc95f80868231dfd25870cbdca8bd7e56f10f731cc870ff56d5de0e520d1
windres --version
bin.rc @C:\Users\█████\min\
  rc         windres@C:\_C++\bin\windres.exe
  id         gnu
  signature  GNU windres (Binutils for MinGW-W64 x86_64, built by Brecht Sanders) 2.38
  checksum   c05e99b5cc8af34317799109b56d6d5f8c30ad2f6cc6d84e93ead51613c08468
g++ -std=c++23 -fmodules-ts -print-search-dirs
g++ -std=c++23 -fmodules-ts -x c++ -v -E -
cxx @C:\Users\█████\min\
  cxx        g++@C:\_C++\bin\g++.exe
  mode       -std=c++23 -fmodules-ts
  id         gcc
  version    12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
  major      12
  minor      1
  patch      0
  signature  gcc version 12.1.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders)
  checksum   df44c4e942030f0f1987240a9d7509e4bc09214423a654fa1b7ccee496c84a11
  target     x86_64-w64-mingw32
  runtime    libgcc
  stdlib     libstdc++
  c stdlib   msvc
  hdr dirs
    c:\_c++\include\c++\12.1.0\
    c:\_c++\include\c++\12.1.0\x86_64-w64-mingw32\
    c:\_c++\include\c++\12.1.0\backward\
    c:\_c++\lib\gcc\x86_64-w64-mingw32\12.1.0\include\
    c:\_c++\include\
    c:\_c++\lib\gcc\x86_64-w64-mingw32\12.1.0\include-fixed\
    c:\_c++\x86_64-w64-mingw32\include\
  lib dirs
    c:\_c++\lib\gcc\x86_64-w64-mingw32\12.1.0\
    c:\_c++\lib\gcc\
    c:\_c++\x86_64-w64-mingw32\lib\x86_64-w64-mingw32\12.1.0\
    c:\_c++\x86_64-w64-mingw32\lib\
    c:\_c++\lib\x86_64-w64-mingw32\12.1.0\
    c:\_c++\lib\
    C:\mingw\lib\x86_64-w64-mingw32\12.1.0\
    C:\mingw\lib\
g++ -std=c++23 -fmodules-ts -finput-charset=UTF-8 -fmodule-mapper=<> -x c++ -E -fdirectives-only -o C:\Users\█████\min\hello.exe.o.ii C:\Users\█████\min\hello.cxx
  > HELLO 1 GCC '' ;
    MODULE-REPO
  < HELLO 1 build2 ;
    PATHNAME .
g++ -std=c++23 -fmodules-ts -finput-charset=UTF-8 -E -x c++ -fpreprocessed -fdirectives-only C:\Users\█████\min\hello.exe.o.ii
g++ -std=c++23 -fmodules-ts -finput-charset=UTF-8 -fmodule-mapper=<> -x c++ -E -fdirectives-only -o C:\Users\█████\min\hello.exe.gcm.ii C:\Users\█████\min\hello.mxx
  > HELLO 1 GCC '' ;
    MODULE-REPO
  < HELLO 1 build2 ;
    PATHNAME .
  > MODULE-IMPORT 'c:\\_c++\\include\\c++\\12.1.0\\string_view'
  < ERROR relative header path ''c:\\_c++\\include\\c++\\12.1.0\\string_view''
C:\Users\█████\min\hello.mxx:3:1: error: unknown Compiled Module Interface: malformed error response
    3 | import <string_view>;
      | ^~~~~~
In module imported at C:\Users\█████\min\hello.mxx:3:1:
c:\_c++\include\c++\12.1.0\string_view: error: failed to read compiled module: Unknown CMI mapping
c:\_c++\include\c++\12.1.0\string_view: note: imports must be built before being imported
c:\_c++\include\c++\12.1.0\string_view: fatal error: returning to the gate for a mechanical issue
compilation terminated.
info: failed to update C:\Users\█████\dir{min\}
```
What am I doing wrong here? What did I miss? I don't recall having to do anything more. I do recall `GCC` stating something like "to use system header units you must explicitly compile them yourself first", _but_ I recall `build2` stating that the build system will do this automatically.

I am on Windows 10 and using the `MinGW` installation for `build2`, if that information matters.

**Comment by Klaim** [comment] 2022-08-05 15:25
Note that even on linux GCC's C++ modules support is not really stable yet. For example last time I checked (it was with gcc 11.2 and in gcc 12 they didn't change a thing related to modules, I believe), header-imports (`import <string_view>;`) didn't link at all when importing the standard library. This might still be a `build2` issue though, or a mix of both.

What happens when you replace the standard header-imports by includes?

Also, which version of `build2` is this?

**Comment by NothcixConfictura** [comment] 2022-08-05 16:05
> Also, which version of `build2` is this?
```
build2 0.16.0-a.0.5ae1fe4cfc96
libbutl 0.16.0-a.0.2d4ca2286c6e
host x86_64-w64-mingw32
Copyright (c) 2014-2022 the build2 authors.
This is free software released under the MIT license.
```

> What happens when you replace the standard header-imports by includes?
It... now says something like this:
```
c:\_c++\include\c++\12.1.0\iostream:40:10: error: cannot determine '#include' translation of c:\_c++\include\c++\12.1.0\istream: malformed error response
   40 | #include <istream>
      |          ^~~~~~~~~
  > INCLUDE-TRANSLATE 'c:\\_c++\\include\\c++\\12.1.0\\bits\\istream.tcc'
  < ERROR relative header path ''c:\\_c++\\include\\c++\\12.1.0\\bits\\istream.tcc''
In file included from c:\_c++\include\c++\12.1.0\iostream:40:
c:\_c++\include\c++\12.1.0\istream:995:10: error: cannot determine '#include' translation of c:\_c++\include\c++\12.1.0\bits\istream.tcc: malformed error response
  995 | #include <bits/istream.tcc>
      |          ^~~~~~~~~~~~~~~~~~
info: failed to update C:\Users\█████\dir{min\}
```
... for every single system headers such as `<vector>` and `<filesystem>`, even the ones in the `bits/` folder, for some reason.

**Comment by Klaim** [comment] 2022-08-05 16:49
I had the mingw install on windows setup already so I tried to reproduce quicklly your problem. I reproduced the initial problem (with g++-11.2). Then I changed the header imports to includes in the global module fragment:
``` 
module;

#include <string_view>
#include <iostream>

export module hello;


export namespace hello {
    void say_hello(const std::string_view &name) {
        std::cout << "Hello, " << name << '!' << std::endl;
    }
}
```

I can reproduce the same errors, so that confirms your issue is not isolated.

I then tried the same thing with an project (not just a buildfile) and see the same issues. So it's same with g++11.2

We'll have to see what @boris-kolpackov  think when he is available again (not for a few weeks) but I highly suspect that the issue comes from g++'s implementation. Right now only msvc's implementation of modules is actually usable, thought there is a macro bug preventing build2 from re-enabling it's support.

**Comment by NothcixConfictura** [comment] 2022-08-06 04:49
> ... suspect that the issue comes from `G++`'s implementation.

This however, without the `build2` integrations, works:
```c++
// lib.cpp
export module lib;

import <iostream>;
import <string_view>;

export namespace lib {
    template<int N>
    inline void func(const std::string_view &str) {
        std::cout << str << ' ' << N << std::endl;
    }
}
```
```c++
// main.cpp
import lib;

int main(int argc, char *argv[]) {
    lib::func<314>("Hi");
    lib::func<159>("Hello");
    return 0;
}
```
Compiled and ran like this:
```bash
# Compile the system headers.
$ g++ -std=c++20 -fmodules-ts -emit-module-interface -c -x c++-system-header iostream string_view

# Compile the user program.
$ g++ -o main.exe -std=c++20 -fmodules-ts lib.cpp main.cpp

# Run the program.
$ main.exe
Hi 314
Hello 159
```
... or this (after removing the binary outputs and the `gcm.cache` directory):
```bash
# Compile the system headers.
$ g++ -std=c++20 -fmodules-ts -emit-module-interface -c -x c++-system-header iostream string_view

# Compile the module interface (and implementation).
$ g++ -std=c++20 -fmodules-ts -emit-module-interface -o lib.o lib.cpp

# Compile the user program.
$ g++ -std=c++20 -fmodules-ts -o main.exe main.cpp lib.o

# Run the program.
$ main.exe
Hi 314
Hello 159
```
So the modules themselves, while only partially supported by GCC, do actually work. I suppose this has something to do with `build2`'s module-mapping system?

**Comment by Klaim** [comment] 2022-08-06 12:57
My understanding is that `build2` tries to use GCC's module mapper, but `build2` also does not compile the same way you did, it does a pre-compilation pass first, as you can see in the verbose report you gave first. I think the issue is somewhere in that part.

**Comment by NothcixConfictura** [comment] 2022-08-06 16:47
Ah, yes, I just observed the verbose output again and was able to reproduce it on the command-line. Apparently `-fmodule-mapper=<>` uses `stdin` and `stdout`, and `build2` thinks that `'c:\\_c++\\include\\c++\\12.1.0\\string_view'` is an invalid relative header path, outputting this to `g++`:
> `< ERROR relative header path ''c:\\_c++\\include\\c++\\12.1.0\\string_view''`

Thus `g++` fails with a malformed response error. I suppose for now I'd have to wait.

**Comment by NothcixConfictura** [comment] 2022-08-07 07:20
Based on my (possibly last) further observation:
From [`compile-rule.cxx`](https://github.com/build2/build2/blob/master/libbuild2/cc/compile-rule.cxx#L1909-L1910):
> ```c++
> // @@ TODO: quoting and escaping.
> ```
... that continues to [this](https://github.com/build2/build2/blob/master/libbuild2/cc/compile-rule.cxx#L1984-L1986):
> ```c++
> tmp.assign (r, b, n);
> r = "ERROR relative header path '"; r += tmp; r += '\'';
> continue;
> ```
... it appears that escaped characters are not yet supported in `build2`'s module-mapping system, but `g++` sends the absolute path with escaped backslashes (_i.e._, `> MODULE-IMPORT 'c:\\_c++\\include\\c++\\12.1.0\\string_view'`) because that's how paths work in Windows, thus confusing `build2`.

**Comment by boris-kolpackov** [comment] 2022-08-16 06:27
Thanks for the report and investigation. I think you are correct, the path quoting and escaping support in the module mapper protocol is still a TODO on the `build2` side. I will try look into this before the next release.

**Comment by boris-kolpackov** [comment] 2023-06-07 12:35
Ok, this has been fixed and the fix is available in the latest staged toolchain. Note that importing headers with paths that contain spaces is still broken due to a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110153

I am going to close this but feel free to reopen if there are still any issues.

**Closed by boris-kolpackov** 2023-06-07 12:35 UTC
Labels: modules
