### ISSUE TITLE
MSYS GCC hangs in `gcc -x c -E -`

### ISSUE THREAD

**Issue by helmesjo** [build2/build2#443] opened 2024-10-30 08:56 UTC
First time I've seen this, but below causes a non-detected deadlock (I assume it waits for `gcc -O2 -x c -E -`).
I am targeting Windows using `gcc`.

The command `gcc -dumpmachine` returns `x86_64-pc-msys`.

```
$ bdep init -C @gcc cc config.c=gcc config.c.coptions="-O2" --wipe --verbose=6
rmdir -r C:\Users\fho\git\b2\build2-FFmpeg\.bdep\tmp\
mkdir C:\Users\fho\git\b2\build2-FFmpeg\.bdep\tmp\
initializing in project C:\Users\fho\git\b2\build2-FFmpeg\
trace: open: PREPARE PRAGMA locking_mode = EXCLUSIVE
trace: open: PRAGMA locking_mode = EXCLUSIVE
trace: open: DEALLOCATE PRAGMA locking_mode = EXCLUSIVE
trace: open: PREPARE BEGIN EXCLUSIVE
trace: open: BEGIN EXCLUSIVE
trace: open: PREPARE SELECT "version", "migration" FROM "main"."schema_version" WHERE "name" = ?
trace: open: SELECT "version", "migration" FROM "main"."schema_version" WHERE "name" = ?
trace: open: DEALLOCATE SELECT "version", "migration" FROM "main"."schema_version" WHERE "name" = ?
trace: open: COMMIT
trace: init: BEGIN
trace: init: PREPARE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."type" = ?
trace: init: SELECT COUNT(*) FROM "configuration" WHERE "configuration"."type" = ?
trace: init: DEALLOCATE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."type" = ?
trace: init: PREPARE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."name" = ?
trace: init: SELECT COUNT(*) FROM "configuration" WHERE "configuration"."name" = ?
trace: init: DEALLOCATE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."name" = ?
trace: init: PREPARE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."path" = ?
trace: init: SELECT COUNT(*) FROM "configuration" WHERE "configuration"."path" = ?
trace: init: DEALLOCATE SELECT COUNT(*) FROM "configuration" WHERE "configuration"."path" = ?
trace: init: COMMIT
C:\build2\bin\bpkg --verbose 6 create -d C:\Users\fho\git\b2\build2-FFmpeg-gcc --name gcc --type target --wipe --no-host-config --no-build2-config cc config.c=gcc config.c.coptions=-O2
trace: cfg_create: creating configuration in C:\Users\fho\git\b2\build2-FFmpeg-gcc\
rm -r C:\Users\fho\git\b2\build2-FFmpeg-gcc\*\
C:\build2\bin\b --verbose 6 config.c=gcc config.c.coptions=-O2 "create('C:\Users\fho\git\b2\build2-FFmpeg-gcc\', cc)"
trace: main: BUILD2_VAR_OVR: <NULL>
trace: main: BUILD2_DEF_OPT: <NULL>
trace: main: loading local C:\Users\fho\.build2\b.options
trace: main: setting BUILD2_VAR_OVR='!config.import.libbuild2_autoconf=C:/Users/fho/git/b2/libbuild2-autoconf-build/module/'
trace: main: work: C:\Users\fho\git\b2\build2-FFmpeg\
trace: main: home: C:\Users\fho\
trace: main: path: C:\msys64\ucrt64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\Program Files\Alacritty;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;C:\ProgramData\chocolatey\bin;C:\Program Files\tre-command\bin;C:\Program Files\CMake\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Git\cmd;C:\Program Files\gitui\bin;C:\Program Files\gsudo\Current;C:\Program Files\dotnet;C:\Users\fho\AppData\Local\Programs\Python\Python312\Scripts;C:\Users\fho\AppData\Local\Programs\Python\Python312;C:\Users\fho\AppData\Local\Programs\Python\Launcher;C:\Users\fho\.cargo\bin;C:\Users\fho\AppData\Local\Programs\Python\Python310\Scripts;C:\Users\fho\AppData\Local\Programs\Python\Python310;C:\Users\fho\AppData\Local\Microsoft\WindowsApps;C:\Users\fho\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\bin;C:\Program Files\Git\mingw64\bin;C:\build2\bin;C:\Users\fho\AppData\Local\Microsoft\WinGet\Links;C:\Users\fho\.dotnet\tools;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\DiagnosticsHub\Collector;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\LLVM\bin;/bin;/bin;/bin
trace: main: type: installed
trace: main: jobs: 32
trace: context: initializing build state
trace: context: original host: 'x86_64-microsoft-win32-msvc14.3'
trace: context: canonical host: 'x86_64-microsoft-win32-msvc14.3'; class: windows
trace: main: buildspec: "create"(C:\Users\fho\git\b2\build2-FFmpeg-gcc\, cc)
trace: main: lifting operation create, id 5
trace: preprocess_create: creating project in C:\Users\fho\git\b2\build2-FFmpeg-gcc\
mkdir C:\Users\fho\git\b2\build2-FFmpeg-gcc\build\
cat >C:\Users\fho\git\b2\build2-FFmpeg-gcc\build\bootstrap.build
cat >C:\Users\fho\git\b2\build2-FFmpeg-gcc\build\root.build
cat >C:\Users\fho\git\b2\build2-FFmpeg-gcc\buildfile
trace: source: sourcing C:\Users\fho\git\b2\build2-FFmpeg-gcc\build\bootstrap.build
trace: config::boot: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: test::boot: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: dist::boot: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: install::boot: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: bootstrap_src: looking for subprojects in C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: main: start meta-operation batch configure, id 3
trace: main: start operation batch <default>, id 1
trace: main: bootstrapped C:\Users\fho\git\b2\build2-FFmpeg-gcc\:
trace: main:   out_base:     C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: main:   src_base:     C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: main:   out_root:     C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: main:   src_root:     C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: main:   forwarded:    false
trace: main: loading C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: config::init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: test::init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: dist::init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: install::init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: source: sourcing C:\Users\fho\git\b2\build2-FFmpeg-gcc\build\root.build
trace: cc::config_init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: c::config_init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: c::guess_init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: cc::core_vars_init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
trace: bin::vars_init: for C:\Users\fho\git\b2\build2-FFmpeg-gcc\
gcc -v
trace: cc::guess: gcc is gcc: 'gcc version 13.3.0 (GCC)'
gcc -O2 -print-multiarch
trace: cc::guess_gcc: gcc doesn's support -print-multiarch, falling back to -dumpmachine
gcc -O2 -dumpmachine
gcc -O2 -x c -E -
```

**Comment by boris-kolpackov** [comment] 2024-10-30 10:27
Note that this is MSYS GCC (`x86_64-pc-msys`) as opposed to MinGW GCC, which, strictly speaking, we don't claim to support. While it would be nice to fix, this is not a priority.

**Comment by boris-kolpackov** [comment] 2024-11-05 09:13
Isn't this a duplicate of #425?

**Closed** 2024-11-05 09:52 UTC
