### ISSUE TITLE
error: unable to execute git: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by wroyca** [build2/build2#243] opened 2022-12-19 21:59 UTC
A somewhat strange problem occurs with bdep on staging:

```bash
> bdep -v new -l c++ -t bare hello

git init -q C:\Users\wroy\Desktop
error: unable to execute git: %1 is not a valid Win32 application
```

*(I'm aware that's not much information to go by, I'll try to isolate this in the next days)*

**Comment by wroyca** [comment] 2022-12-19 23:18
Some additional information: `vcvarsall.bat` (and the x64 Native Tolls command prompt) sometimes runs in x86 when the machine has been modified a lot. This is especially apparent if the machine has undergone registry changes. Unfortunately, I don't know exactly what changes cause this to happen and will have to investigate further.

**Comment by boris-kolpackov** [comment] 2022-12-20 05:23
Another thing that would be helpful is to confirm "who's" `git` is being executed. In particular, `bdep` (unlike `bpkg`) does not attempt to use `build2`-bundled `git`. Can you run:

```
> where git
```

You may also want to try to run the above command directly and see if you get the same result:

```
git init -q C:\Users\wroy\Desktop
```

**Comment by wroyca** [comment] 2022-12-20 05:55
> Another thing that would be helpful is to confirm "who's" `git` is being executed. In particular, `bdep` (unlike `bpkg`) does not attempt to use `build2`-bundled `git`. Can you run:
> 
> ```
> > where git
> ```
> 
> You may also want to try to run the above command directly and see if you get the same result:
> 
> ```
> git init -q C:\Users\wroy\Desktop
> ```

Unfortunately, I deleted everything with a restore point as I had things to do and couldn't afford to wait -- Fortunately, I ran `git init -q C:\Users\wroy\Desktop` beforehand and it ran correctly without any major problems. One behavior I noticed is that bdep was creating the directory (hello) before throwing this error, so in the runtime flow, the error was happening shortly after. I'll try to reproduce this problem on a test machine, but I don't think I'll have time with Christmas coming up.🎅

**Comment by boris-kolpackov** [comment] 2022-12-20 06:39
> I'll try to reproduce this problem on a test machine, but I don't think I'll have time [...]

Ok, I am going to close this but feel free to reopen if you do manage to reproduce it and provide more information.

**Comment by wroyca** [comment] 2022-12-30 19:16
@boris-kolpackov Permission doesn't allow to reopen a issue, but I managed to hit it again:

```
C:\Users\wroy\Desktop\foo>where git
C:\build2\bin\git.exe
C:\Program Files\Git\cmd\git.exe

C:\Users\wroy\Desktop\foo>git init -q C:\Users\wroy\Desktop\foo
Access is denied.

C:\Users\wroy\Desktop\foo>b
error: unable to execute git: %1 is not a valid Win32 application
```

**Comment by wroyca** [comment] 2022-12-30 19:18
Here is the git executable that build2 added in C:\build2\bin
[git.zip](https://github.com/build2/build2/files/10326008/git.zip)

**Comment by boris-kolpackov** [comment] 2023-01-05 09:30
You should normally not use `build2`'s `git` directly -- it is provided only to be used by `bpkg` to fetch from `git` repositories. This is the reason why in the post-installation instructions we suggest adding `c:\build2\bin` as the *last* entry in `PATH`.

Try the following and see if it makes a difference:

```
> set "PATH=C:\Program Files\Git\cmd;%PATH%"

>where git
C:\Program Files\Git\cmd\git.exe
C:\build2\bin\git.exe

>git init -q C:\Users\wroy\Desktop\foo
```

**Comment by wroyca** [comment] 2023-01-05 14:16
> You should normally not use `build2`'s `git` directly -- it is provided only to be used by `bpkg` to fetch from `git` repositories. This is the reason why in the post-installation instructions we suggest adding `c:\build2\bin` as the _last_ entry in `PATH`.

`C:\build2\bin` is actually the last entry in my PATH. Now as to why Windows show `C:\Program Files\Git\cmd\git.exe` above ... 

That said, on a Windows factory reset, I can reproduce it consistently, the git binary in build2-baseutils-0.16.0-a.0-x86_64-windows.zip is simply not a valid Windows binary -- something is wrong with the linking process and screws up the binary sections so the supplychain is broken by default

For now, the solution is to replace it with https://git-scm.com/download/win (/mingw32/git.exe and its DLL)

> Try the following and see if it makes a difference:
> 
> ```
> > set "PATH=C:\Program Files\Git\cmd;%PATH%"
> 
> >where git
> C:\Program Files\Git\cmd\git.exe
> C:\build2\bin\git.exe
> 
> >git init -q C:\Users\wroy\Desktop\foo
> ```

My https://git-scm.com/download/win installation work fine here, but build2 still reach to error: unable to execute git: %1 is not a valid Win32 application

**Comment by boris-kolpackov** [comment] 2023-01-05 15:49
Don't use `build2's` bundled `git` for `git init`.

**Comment by wroyca** [comment] 2023-02-13 04:14
Closing. Hasn't happened again for a long time now

**Closed** 2023-02-13 04:14 UTC
Labels: bug
