### ISSUE TITLE
`brep-help` fails with `broken pipe` error

### ISSUE THREAD

**Issue by karen-arutyunov** [build2/build2#392] opened 2024-06-17 12:37 UTC
If to run `bdep help new` and to quit before scrolling to the end of the man page, then the command fails as follows:

```
$ bdep help new
error: pager failed: broken pipe
```

Reproduces at least on Linux and MacOS.

**Comment by Klaim** [comment] 2024-06-17 12:49
I just tried that with 
```
$ bdep --version
bdep 0.17.0-a.0.c8a08cc0ce55
libbpkg 0.17.0-a.0.f42bdebb7037
libbutl 0.17.0-a.0.a093e86f9911
[...]

$ b --version
build2 0.17.0-a.0.63bd5b824590
libbutl 0.17.0-a.0.a093e86f9911
host x86_64-microsoft-win32-msvc14.3
[...]
```
on Windows (using git-bash, powershell and cmd), I get 
```
error: pager failed: invalid argument
```

**Comment by Klaim** [comment] 2024-06-17 12:51
Note that I didnt remark that issue so far (I've used that version since it was published, in several projects) and now I realize it doesnt appear in the cases I used recently: `bdep help config`, `bdep help status`, `bdep help init` etc. so probably it's specific to `new`

**Comment by wroyca** [comment] 2024-06-17 18:29
Can't reproduce under Fedora 40 with Kitty

```
build2 0.17.0-a.0.1455bfe7be36
libbutl 0.17.0-a.0.01619db789f7
host x86_64-redhat-linux-gnu
Copyright (c) 2014-2024 the build2 authors.
```

**Comment by boris-kolpackov** [comment] 2024-06-21 07:25
Fixed in the latest staged toolchain.

**Closed by boris-kolpackov** 2024-06-21 07:25 UTC
