### ISSUE TITLE
bpkg install does not install all header files when packaging glew

### ISSUE THREAD

**Issue by AnandR-2D2** [build2/build2#149] opened 2021-04-14 15:58 UTC
I'm testing out build2 by creating a glew package using https://github.com/nigels-com/glew.git as the upstream.
I'm currently able to build the package however, `glew.h` is never installed with `bpkg install`. Other headers `wglew.h`, `eglew.h` and `glxew.h` all install as expected but I'm unable to understand why only this header is skipped even when `glew.h` is in the same directory (`upstream/include`) as others.

I tried to manually add a rule only for this header file as follows, which also did not work.
```
../upstream/include/GL/h{glew}:
{
    install = include/GL/
}
```

I tested the `bpkg install` using the already packaged `googletest` as well as a local header only library.
It works ok in these cases.

PS: Need to manually run `make` inside the auto folder of `upstream` to generate the required headers in case anyone wants to try it out. I currently don't have another solution.

**Comment by AnandR-2D2** [comment] 2021-04-14 16:37
Update 1:
The header file `glew.h` is not installed when installing from a `bdep` initialised configuration.
When the configuration is initialised using `bpkg create` followed by `bpkg build`, the header file installs correctly.

**Comment by boris-kolpackov** [comment] 2021-04-15 11:11
Do you have a repository of your packaging attempt that I could try?

**Comment by AnandR-2D2** [comment] 2021-04-15 17:12
@boris-kolpackov I just created this repo for a quick trial.

**Comment by Klaim** [comment] 2021-04-15 18:00
Looks like the issue is only visible on Linux. On Windows it compiles with lots of symbol linkage inconsistency warning, then fails to link because of a few missing symbols.
On linux I can reproduce your issue.

**Comment by Klaim** [comment] 2021-04-15 18:10
Note that the error I get on Linux is `fatal error: 'GL/glu.h' file not found` and that file indeed doesnt exist. Am I missing something?

**Comment by boris-kolpackov** [comment] 2021-04-16 13:20
I took a look at your `buildfile` and it appears to be using a deprecated approach of pulling stuff from `upstream/` using `..\upstream\...` paths. You can make it work but it will be messy (and you need to have a pretty good understanding of the build model).

Instead, the recommended approach is to recreate the same structure as upstream using `bdep-new` and then "pull" the source files into right places with [symlinks](https://build2.org/article/symlinks.xhtml) (or simply by copying them if you are against symlinks for some reason). All the pinned examples in [build2-packaging](https://github.com/build2-packaging/) use this approach.

For the first step (recreate the structure using `bdep-new`), see the [SOURCE LAYOUT](https://build2.org/bdep/doc/bdep-new.xhtml#src-layout) section which gives examples of the various structures and how to recreate them. The one that we want is this:

```
# libhello/{include/hello,src}/

$ bdep new -l c++ -t lib,split,subdir=hello,no-subdir-source libhello

$ tree libhello/
libhello/
├── include/
│   └── hello/
│       └── hello.hxx
└── src/
    └── hello.cxx
```

Here is the command line that I came up with (I've also suppressed `version.h.in` which we don't need):

```
bdep new -l c -t lib,split,subdir=GL,no-subdir-source,no-version glew
```

The next steps would be:

1. Replace generated `.h` files in `include/GL/` with symlinks to `../../upstream/include/GL/*.h`

2. Replace the generated `glew.c` file in `src/` with symlink to  `../upstream/src/glew.c`

3. Rename generated `tests/basics/` to `tests/glewinfo/` and replace the source with symlink to `../../upstream/src/glewinfo.c`

4. Tweak `src/buildfile` with any extra options (like `-D`), libraries to link, etc., -- the boilerplate shouldn't require much changing and should do the right thing (note that in this layout there is also `include/GL/buildfile`).

Let me know how it goes -- I would like to copy a version of these steps to our packaging guide to help others with similar issues.

**Comment by AnandR-2D2** [comment] 2021-04-17 16:13
@boris-kolpackov Thank you very much for the detailed explanation! This really helps! Following your exact solution with the links worked! Headers are installed correctly with a `bdep` as well `bpkg` initialised configs. It would be great to add this as documentation.

To be honest doing it this way means less typing by hand. The generated `buildfile`s in `include/GL` and `src` are sufficient and only required add the appropriate the defines.

**Comment by boris-kolpackov** [comment] 2024-05-08 05:42
FYI, we now have a comprehensive packaging guide that covers the recommended approach in detail: https://build2.org/stage/build2-toolchain/doc/build2-toolchain-packaging.xhtml

So I am going to close this issue.

**Closed by boris-kolpackov** 2024-05-08 05:42 UTC
Labels: not our bug
