### ISSUE TITLE
Unable to satisfy dependency from archive

### ISSUE THREAD

**Issue by boris-kolpackov** [build2/build2#183] opened 2022-03-14 13:20 UTC
Unable to build both a dependency and a dependent from archives with a single `bpkg-pkg-build` invocation:

```
$ bpkg create -d test cc
$ cd test

$ bpkg build odb-2.5.0-b.21.tar.gz libcutl-1.11.0-b.9.tar.gz libstudxml-1.1.0-b.10.tar.gz
error: no package available for dependency libstudxml of package odb
info: while satisfying odb/2.5.0-b.21

$ bpkg build libstudxml-1.1.0-b.10.tar.gz libcutl-1.11.0-b.9.tar.gz odb-2.5.0-b.21.tar.gz
error: no package available for dependency libstudxml of package odb
info: while satisfying odb/2.5.0-b.21
```

Building them individually in the correct order works:

```
$ bpkg build libstudxml-1.1.0-b.10.tar.gz
$ bpkg build libcutl-1.11.0-b.9.tar.gz
$ bpkg build odb-2.5.0-b.21.tar.gz
```

**Comment by karen-arutyunov** [comment] 2023-07-28 16:56
Duplicate of #303.

**Closed** 2023-07-28 16:57 UTC
Labels: bug
